export const MAX_MEETING_TITLE_LENGTH = 20;
export const MAX_MEETING_AGENDA_LENGTH = 30;
export const MAX_MEETING_LOCATION_LENGTH = 20;
export const MIN_MEETING_PARTICIPANTS = 2;
export const MAX_MEETING_PARTICIPANTS = 8;
